# Generated by Django 5.2.7 on 2025-10-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('item', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
