# Generated by Django 5.2.7 on 2025-10-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='data',
            new_name='date',
        ),
    ]
