# Generated by Django 5.2.7 on 2025-11-04 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0003_category_alter_expense_options_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='世帯名')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='費目名'),
        ),
        migrations.AddField(
            model_name='category',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='kakeibo.household'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('household', 'name')},
        ),
    ]
