# Generated by Django 5.2.7 on 2025-11-06 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0004_household_alter_category_name_category_household_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='対象月(1日固定)')),
                ('amount', models.PositiveIntegerField(verbose_name='予算(円)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='kakeibo.category')),
            ],
            options={
                'ordering': ['-month', 'category__name'],
                'unique_together': {('month', 'category')},
            },
        ),
    ]
