# Generated by Django 5.2.7 on 2025-11-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0005_budget'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.DateField(db_index=True, verbose_name='対象月（1日固定）'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['month'], name='kakeibo_bud_month_d03e91_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['category'], name='kakeibo_bud_categor_f672a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('month', 'category'), name='uniq_budget_month_category'),
        ),
    ]
