# Generated by Django 5.2.7 on 2025-11-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0006_alter_budget_unique_together_alter_budget_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('source', models.CharField(max_length=100, verbose_name='収入源')),
                ('amount', models.PositiveIntegerField(verbose_name='金額(円)')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='メモ')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
